version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      #command: gunicorn main.wsgi -b 0.0.0.0:8000
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn main.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./backend:/app/backend/
      - ./backend/static:/static
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    command: npm run build
    volumes:
      - ./frontend:/app/frontend/
    depends_on:
      - backend
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/static:/static
      - ./frontend/dist://usr/share/nginx/html:ro
    depends_on:
      - backend
